### ISSUE TITLE
Support `readonly` options in services.xxx.volumes

### ISSUE THREAD

**Issue by osddeitf** [linktohack/helm-stack#1]
Whenever I want to mount volumes as readonly (for better security reason):
```yaml
volumes:
  - testnfs:/data
Deployment:
  spec:
    template:
      spec:
        containers:
        - volumeMounts:
          - name: testnfs
            mountPath: /data
            readOnly: true
```
It's cumbersome so I think it would be better to having support for `[SOURCE:]TARGET[:MODE]` as specified in [docker-compose short syntax](https://docs.docker.com/compose/compose-file/#short-syntax-3).
Likewise, the above example would be pretty much simpler:
```yaml
volumes:
  - testnfs:/data:ro

**Comment by linktohack** [comment]
Good idea, tell me if you want to give it a try :D

**Comment by linktohack** [comment]
With the 1.8.3 release, merging strategy is hopefully better, the above script can be simplified a little...

```yaml
volumes:
  - testnfs:/data
Deployment:
  spec:
    template:
      spec:
        containers:
        - volumeMounts:
          - readOnly: true
```
Still open for the PR :D
