### ISSUE TITLE
ingress - multiple paths no default backend

### ISSUE THREAD

**Issue by finitelife** [linktohack/helm-stack#8]
Works:
```
    Ingress:
      default:
        spec: {rules: [http: {paths: [{path: /, pathType: Prefix}]}]}
```
Doesn't work:
```
    Ingress:
      default:
        spec:
          rules:
            - http:
                paths:
                  - {path: /, pathType: Prefix}
                  - {path: "/api/v0/(create|read|update|delete)/?", pathType: Prefix}
```
